[package]
name = "alba-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alba-core = { path = "../alba-core" }
alba-executors = { path = "../alba-executors" }
async-trait.workspace = true
blake3.workspace = true
globset.workspace = true
notify.workspace = true
notify-debouncer-full.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
which.workspace = true

[dev-dependencies]
alba-executors = { path = "../alba-executors", features = ["test-util"] }
tempfile.workspace = true
