[package]
name = "alba-executors"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-util = []

[[bin]]
name = "fake-plugin"
path = "tests/support/fake_plugin.rs"

[dependencies]
alba-shell = { path = "../alba-shell" }
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["signal"] }

[dev-dependencies]
tempfile.workspace = true
