[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/jdevelop-io/alba"

[workspace.dependencies]
arboard = "3"
assert_cmd = "2"
async-trait = "0.1"
blake3 = "1"
clap = { version = "4", features = ["derive"] }
crossterm = { version = "0.28", features = ["event-stream"] }
futures = "0.3"
glob = "0.3"
globset = "0.4"
ignore = "0.4"
miette = "7"
nix = "0.29"
notify = "8"
notify-debouncer-full = "0.7"
os_pipe = "1"
owo-colors = "4"
portable-pty = "0.9"
predicates = "3"
ratatui = "0.29"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
which = "7"
insta = "1"
tempfile = "3"
